### ISSUE TITLE
Delivering bundles to OpenShift Community Catalog with Image digest for usage in restricted env

### ISSUE THREAD

**Issue by muellerfabi** [rabbitmq/OLM-Package-Repo#5]
### Is your feature request related to a problem? Please describe.

At the moment it is not possible to deploy the operator on an OpenShift cluster that is aig-gapped / running on a restricted network.
In order to make it possible, the bundle must contain Image Digests instead of Tags as well as a list of all related images, i.e. the ones that deployed as an instance. [1]

[1] https://docs.openshift.com/container-platform/4.12/operators/admin/olm-restricted-networks.html

### Describe the solution you'd like

All three rabbitmq operator bundles should be delivered to OpenShift Community Catalog using Image digests.

**Comment by Zerpet** [comment]
@DanielePalaia since you were making changes on this workflow recently, perhaps this issue is a low hanging fruit if we just use `kbld` [1] ?

[1] https://carvel.dev/kbld/

**Comment by DanielePalaia** [comment]
Linking these operators as they are implementing this feature (we also need to add a relatedImages group field I think)

https://github.com/rabbitmq/community-operators-prod/blob/main/operators/egressip-ipam-operator/1.2.4/manifests/egressip-ipam-operator.clusterserviceversion.yaml

https://github.com/rabbitmq/community-operators-prod/blob/main/operators/grafana-operator/5.6.0/manifests/grafana-operator.clusterserviceversion.yaml

**Comment by DanielePalaia** [comment]
@Zerpet I integrated kbld. it seems working good for our purpose but it is adding an annotation and reformatting the .yaml. The tests are passing tough but we need to see if everything will be fine during the operatorhub/openshift marketplace submissions!

**Comment by DanielePalaia** [comment]
Hi @muellerfabi in the last operator release we provided the sha of the operator image instead of the tag: https://github.com/rabbitmq/community-operators-prod/blob/main/operators/rabbitmq-cluster-operator/2.8.0/manifests/rabbitmq.clusterserviceversion.yaml

I know this issue is now old and maybe not relevant to you anymore, but if you have the opportunity to test it let us know. Thanks!

**Comment by muellerfabi** [comment]
Thank you! No worry this issue is still relevant for us. Finally we can upgrade without the hassle to rebuild the catalog 😊

Will the next release of rabbitmq-messaging-topology-operator also come with digests ?

**Comment by DanielePalaia** [comment]
@muellerfabi Yes hopefully in the next v1.14.0 release.

Let us know in case of issues! Thanks!

**Comment by DanielePalaia** [comment]
Hi @muellerfabi we also published the messaging topology operator with the digest in 1.14.1:

https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/4546

I'll cose this issue, let us know in case of any issues
